controllers:
    resource: ../src/Controller/
    type: attribute
task_complete:
    path: '/task/{id}/complete'
    controller: 'App\Controller\TaskController::complete'
    methods: ['POST']

update_task_status:
    path: '/task/{id}/update-status'
    controller: 'App\Controller\TaskController::updateTaskStatus'
client_print:
    path: /categorie/show/{id}/download
    controller: App\Controller\CategorieController::downloadPdf
    methods: GET
